#####################################################################
# Codecov configuration.
#####################################################################
ignore:
    - "**/etc/.*"
    - "**/src/app.js"
    - "**/themes/.*"
    - "**/routes/.*"
    - "**/.circleci/.*"
    - "**/*.stories.js"
    - "**/*.spec.js"
    - "**/*.scss"
    - "**/*.svg"
